### ISSUE TITLE
Főoldal

### ISSUE THREAD

**Issue by ImreTheFifth** [flowacademyhu/kappa-konyhatunder#2]
Mint felhasználó aki szeretné megkezdeni az applikácó használatát, szeretnék egy főoldalra érni, ahol kiválaszthatom, hogy miként folytatnám a használatot
AC:
-legyen egy főoldal a már meglévő layoutnak megfelelően #1 
-a főoldal tartalmazzon 3 gombot 
        1. recept keresése hozzávaló alapján
	2. recept keresése kritériumok alapján
        3. recept hozzáadása
	
Estimated time: XS
(Márton és Jonka)
- [x] Routing
- [x] Gombok

**Comment by 6uliver** [comment]
Minden task kész a leírásban, de nincs PR. Itt mi hiányzik? Ha nincs több task, akkor mergeljük, zárjuk, ha van még függő task, akkor vegyétek föl, hogy látszódjon mit kell még megcsinálni. @DanMaKappa88 @jonkapotkivanok
