### ISSUE TITLE
#13 MainPage design javítása

### ISSUE THREAD

**Issue by jonkapotkivanok** [flowacademyhu/kappa-konyhatunder#24]
Kijavítani a nem túl igényes card menü designt.
- [x] Button-ra cserélni a cardokat. @ltamas123 @jonkapotkivanok 
- [x] Css-t szerkeszteni hozzá. @ltamas123 @jonkapotkivanok

**Comment by ImreTheFifth** [comment]
branchelési issue miatt nincs még PR rá, hiba javítás IP
