### ISSUE TITLE
Új kategória hozzáadása a meglévők mellé

### ISSUE THREAD

**Issue by szabo-peter** [flowacademyhu/kappa-konyhatunder#29]
Ha a felhasználó olyan kategóiát szeretne hozzáadni, ami nincs a listában, akkor azt hozzá tudja adni. 

Backend: 
- [x] Endpoint létrehozása @szabo-peter 
- [x] Új kategória elmentése @szabo-peter 

Frontend: 
- [x] A kategórialistánál új input mező létrezhozása egy gombbal. @itsIMITRI 
- [x] Popup ablak a sikeres mentésről.

**Comment by 6uliver** [comment]
Látom review-ba került, de nincs PR, amit nézhetnénk. Kérlek csinálj egyet, valamint linkeld az issue-hoz.
