### ISSUE TITLE
#BUG UI oldali validáció recept felvételénél

### ISSUE THREAD

**Issue by szabo-peter** [flowacademyhu/kappa-konyhatunder#31]
- [x] Sikertelen recept beküldésnél nincs visszajelzés a felhasználó felé. @DanMaKappa88 
- [x] Kötelező mezők validációja. @DanMaKappa88 
- [x] Kötelező mezők elé egy piros figyelemgelhívó jel, jelezve, hogy kötelező.  @DanMaKappa88

**Comment by ImreTheFifth** [comment]
@DanMaKappa88  @szabo-peter a ticket mentori review-n van, viszont nincs hozzá linkelve PR, illetve nem is látok semmit amit hozzá lehetne linkelni. Kérlek ezt pótoljátok mielőbb!

**Comment by DanMaKappa88** [comment]
@ImreTheFifth  done
