### ISSUE TITLE
#FIX -Hiányzó logok létrehozása backenden

### ISSUE THREAD

**Issue by itsIMITRI** [flowacademyhu/kappa-konyhatunder#41]
- [x] Logok lértehozása backend-en. @szabo-peter @itsIMITRI

**Comment by Godfrid** [comment]
Nezzetek meg, de szerintem ez a logger is megeszik .class parametereket a logolasnal es szepen hozza tudja adni a source class-t is.

**Comment by szabo-peter** [comment]
Közben észrevettem, hogy alapból kilogolja, hogy hol volt a log, így kivettem a plusz feliratokat a bug fix-es issueban.
