### ISSUE TITLE
Kép feltöltése recept hozzáadásánál

### ISSUE THREAD

**Issue by ImreTheFifth** [flowacademyhu/kappa-konyhatunder#5]
Mint egy felhasználó, aki szeretne receptet hozzáadni, szeretném, ha képet is tudnék feltölteni az elkészített ételről.
Előfeltétel: https://github.com/flowacademyhu/kappa-konyhatunder/issues/4
AC:
-a recept feltöltési formot szeretnénk fejleszteni, így kerüljön egy képfeltöltési lehetőség is az opciók közé
-a feltöltés ne azonnal történjen meg, amint kiválasztják a fájlt, az csak a recept elküldése gomb lenyomásával induljon el
-lehessen törölni a feltöltés kijelölését
-ez nem kötelező része a receptnek
-viszont nagyban megnöveli egy recept elkészítésének esélyét, így mindenképpen ajánlott. Ennek érdekében, ha valaki kép nélkül szeretne feltölteni egy receptet, az elküldés gomb megnyomását követően egy felugróablak kérdezze meg, hogy biztos-e, hogy kép nélkül szeretné feltölteni a receptet.
-sikeresség esetén a kép legyen eltárolva és a recepthez kötve, hogy később meg tudjuk jeleníteni

- [x] backend felkészitése a kép fogadására @ltamas123 
- [x] eltárolni a recepthez tartozó képet az adatbázisban @ltamas123 

frontend:
- [x] form bővitése képfeltöltési lehetőséggel @jonkapotkivanok 
- [x] előugró ablak ha nem töltöttek fel képet @jonkapotkivanok

**Comment by ImreTheFifth** [comment]
hahó @jonkapotkivanok , @ltamas123 !
Ő miért került vissza todo-ba? A progress bar szerint már 3 kész is van a négy altaskból. Jött valami blokkoló tényező?

**Comment by ltamas123** [comment]
kb kész van az előugró ablakot is max 1 óra alatt bele tudnánk tenni viszont ez a kicsit átalakitja az adatok küldését backend felé és mindenki a addRecipeForm fájlon dolgozott ma és addig nem akartuk betenni amig az övék nincs bent mert akkor minden conflictolt volna mindennel és arra gondoltunk hogy mivel arra a fájlra erőteljesen ráférne a refact ezt tennénk be utoljára a rafacttal együtt de reggel még ezt úgy is megakartam veled beszélni

**Comment by ImreTheFifth** [comment]
@ltamas123 Rendben, köszi, akkor holnap megdumáljuk! Addig is jó pihit! :)
