### ISSUE TITLE
Új hozzávaló feltöltése recept hozzáadásánál

### ISSUE THREAD

**Issue by ImreTheFifth** [flowacademyhu/kappa-konyhatunder#6]
A felhsználók nem mindig találják meg a megfelelő alapanyagot a listában, mivel az még nem volt használva/feltöltve. Mint egy felhasználó, ilyen esetben szeretném hozzáadni a szükséges alapanyagot.
Előfeltétel: https://github.com/flowacademyhu/kappa-konyhatunder/issues/4
AC:
-új alapanyag hozzáadására a recept felvitelénél van lehetőség
-a hozzávaló kiválasztása pontnál a formon legyen egy 'Nem talál egy hozzávalót?' szöveg, valamint alatta egy gomb, amivel hozzá tud adni újat
-a gomb lenyomása után a gomb helyén jelenlenek meg a beviteli mezők: hozzávaló neve, valamint lehessen kiválasztani, hogy milyen mértékegységű legyen
-mértékegységnél csoportokat lehessen kiválasztani, pl hogy tömeg mértékegységet, vagy darabot esetleg folyadékot vinne fel. Ez később a https://github.com/flowacademyhu/kappa-konyhatunder/issues/4 ticketben említett logika alapján adja meg a választható mértékegységet
-legyen egy gomb amivel hozzáadja az alapanyagot
-alapanyag hozzáadása után ne töltsük újra az egész oldalt, viszont töltsük ki az éppen most felvitt alapanyaggal és az alapértelmezett mértékegységgel az alapanyag hozzáadása sort

Backend:
- [x] endpoint létrehozása @szabo-peter @itsIMITRI 
- [x] új hozzávaló elmentése @szabo-peter @itsIMITRI 
- [x] validálás @szabo-peter @itsIMITRI

Frontend: 
- [x] Új hozzávaló létrehozásához szükséges input mező létrehozása @ltamas123 @jonkapotkivanok 
- [x] gomb, amivel be lehet küldeni az új hozzávalót. @ltamas123 @jonkapotkivanok 
- [x]  alapanyag hozzáadása után ne töltsük újra az egész oldalt, viszont töltsük ki az éppen most felvitt alapanyaggal és az alapértelmezett mértékegységgel az alapanyag hozzáadása sort @ltamas123 @jonkapotkivanok 
- [x] form design @jonkapotkivanok

**Comment by Godfrid** [comment]
Majd itt az ingrident service-ben a  public IngredientDTO getIngredient(String id)  if-jeit alakitsatok at else if-es re, mivel logikailag csak az egyik ag futhat le, felesleges minden esetet mindig vegig checkolni.

**Comment by szabo-peter** [comment]
Rendben, a nyitott BUG-os issue-ban javítottam.
