### ISSUE TITLE
Recept oldal - pdf generálása a receptről

### ISSUE THREAD

**Issue by ImreTheFifth** [flowacademyhu/kappa-konyhatunder#61]
Felhasználóként szeretném digitális formában letölteni a receptet, ha megtetszik.

AC:
-generáljuk ki a receptet pdf formátumba, így el tudja küldeni, ki tudja nyomtatni a felhasználó

**Comment by 6uliver** [comment]
Ajánlott library: https://parall.ax/products/jspdf
