### ISSUE TITLE
Recept oldal - pdf generálása a bevásárlólistáról

### ISSUE THREAD

**Issue by ImreTheFifth** [flowacademyhu/kappa-konyhatunder#62]
Felhasználóként nem csak a recept kinyerésére szeretnék lehetőséget, hanem esetlegesen csak a bevásárlólistáról, ami a recepthez kell.

AC:
- [x] a hozzávalók külön is kigenerálhatók legyenek egy pdf-be
- [x] kritérium alapján való keresésnél ez legyen az egész hozzávaló lista
- [x] ha a felhasználó megadta az otthon fellelhető hozzávalókat, akkor a pdf csak azokat az egységeket tartalmazza, amik szerepelnek a recepten, de nincsenek a felhasználó által megadott listán

**Comment by 6uliver** [comment]
Ajánlott library: https://parall.ax/products/jspdf
