### ISSUE TITLE
[FIX STAGING] - Cache bug

### ISSUE THREAD

**Issue by szabo-peter** [flowacademyhu/kappa-konyhatunder#72]
- [x] Staging ne cachelje a lekért adatokat. 

Help: https://www.baeldung.com/spring-mvc-cache-headers   
5. pont.

**Comment by ImreTheFifth** [comment]
hali @ltamas123 !
Ez az issue closed lett és a pull requestje is merged állapotban van. Ezek alapján ez tovább mozgatható a boardon, vagy rosszul gondolom? Sikerült megoldani?

BTW imádom a pull request nevét! :D :D :D

**Comment by szabo-peter** [comment]
@ImreTheFifth  Sajnos nem oldotta meg a problémát. Teamsen írt Tomi az eredeti post alá, ahol ezt a megoldást javasolták a mentorok, nagyon úgy tűnik, hogy ez a google cloud hülyesége lesz.

**Comment by szabo-peter** [comment]
@ltamas123 Sikeresen megoldotta. :)
